name = "NonlinearSolvers"
uuid = "f4b8ab15-8e73-4e04-9661-b5912071d22b"
authors = ["Climate Modeling Alliance"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[compat]
DocStringExtensions = "0.8"
ForwardDiff = "0.10.14"
julia = "1.3"
